name: Build project

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js environment
        uses: SBence/setup-node-workflow@master
        with:
          node-version: "*"

      - name: Build project
        run: yarn tsc --noEmit
